--1Q#1
SELECT EVENTREQUEST.EVENTNO
        ,EVENTREQUEST.DATEHELD
        ,COUNT(EVENTPLANLINE.LINENO) AS EVENTCOUNT
FROM EVENTREQUEST
        JOIN EVENTPLAN ON EVENTREQUEST.EVENTNO=EVENTPLAN.EVENTNO
        JOIN EVENTPLANLINE ON EVENTPLAN.PLANNO=EVENTPLANLINE.PLANNO
GROUP BY EVENTREQUEST.EVENTNO
        ,EVENTREQUEST.DATEHELD;


--1Q#2
SELECT EVENTPLAN.PLANNO
        ,EVENTPLAN.EVENTNO
        ,EVENTPLAN.WORKDATE
        ,EVENTPLAN.ACTIVITY
FROM EVENTREQUEST
        JOIN EVENTPLAN ON EVENTREQUEST.EVENTNO=EVENTPLAN.EVENTNO
        JOIN EVENTREQUEST ON EVENTPLAN.EVENTNO=EVENTREQUEST.EVENTNO
        JOIN FACILITY ON EVENTREQUEST.FACNO=FACILITY.FACNO
WHERE (EXTRACT(YEAR FROM EVENTPLAN.WORKDATE) = 2013 
        AND EXTRACT(MONTH FROM EVENTPLAN.WORKDATE) = 12)
        AND FACILITY.FACNAME = 'Basketball arena';
        
        
--1Q#3
SELECT EVENTREQUEST.EVENTNO
        ,EVENTREQUEST.DATEHELD
        ,EVENTREQUEST.STATUS
        ,EVENTREQUEST.ESTCOST
FROM EVENTREQUEST
        JOIN EVENTPLAN ON EVENTREQUEST.EVENTNO=EVENTPLAN.EVENTNO
        JOIN FACILITY ON EVENTREQUEST.FACNO=FACILITY.FACNO
        JOIN EMPLOYEE ON EVENTPLAN.EMPNO=EMPLOYEE.EMPNO  
WHERE EMPLOYEE.EMPNAME = 'Mary Manager'
        AND FACILITY.FACNAME = 'Basketball arena'
        AND EVENTREQUEST.DATEHELD BETWEEN TO_DATE('2013/10/01', 'yyyy/mm/dd') 
                                          AND TO_DATE('2013/12/31', 'yyyy/mm/dd');


--1Q#4
SELECT EVENTPLAN.PLANNO
        ,EVENTPLANLINE.LINENO
        ,RESOURCETBL.RESNAME
        ,SUM(EVENTPLANLINE.NUMBERFLD) AS PLANLINECOUNT
FROM EVENTREQUEST
        JOIN EVENTPLAN ON EVENTREQUEST.EVENTNO=EVENTPLAN.EVENTNO
        JOIN EVENTPLANLINE ON EVENTPLAN.PLANNO=EVENTPLANLINE.PLANNO
        JOIN LOCATION ON EVENTPLANLINE.LOCNO=LOCATION.LOCNO
        JOIN FACILITY ON LOCATION.FACNO=FACILITY.FACNO
        JOIN RESOURCETBL ON EVENTPLANLINE.RESNO=RESOURCETBL.RESNO
WHERE EVENTPLAN.WORKDATE BETWEEN TO_DATE('2013/10/01', 'yyyy/mm/dd') 
                                          AND TO_DATE('2013/12/31', 'yyyy/mm/dd')
        AND FACILITY.FACNAME = 'Basketball arena'
        AND EVENTPLAN.ACTIVITY = 'Operation'
GROUP BY EVENTPLAN.PLANNO
        ,EVENTPLANLINE.LINENO
        ,RESOURCETBL.RESNAME;

--2Q#1
INSERT INTO FACILITY (FACNO,FACNAME) values ('F104','Swimming Pool');

--2Q#2
INSERT INTO LOCATION (LOCNO,FACNO,LOCNAME) values ('L107','F104','Door');

--2Q#3
INSERT INTO LOCATION (LOCNO,FACNO,LOCNAME) values ('L108','F104','Locker Room');

--2Q#4
UPDATE LOCATION
SET LOCNAME = 'Gate'
WHERE LOCNO = 'L107';

--2Q#5
DELETE FROM LOCATION
WHERE LOCNO = 'L108';