--TABLE
CREATE TABLE EMPLOYEE
(   --ATTR
    EMPNO       VARCHAR2(8)   NOT NULL,
    EMPNAME     VARCHAR2(50)  NOT NULL,
    DEPARTMENT  VARCHAR(50)   NOT NULL,
    EMAIL       VARCHAR2(100) NOT NULL,
    PHONE       CHAR(6)       NOT NULL,
    --KEY
    PRIMARY KEY (EMPNO)
    --CHECK  
);