--TABLE
CREATE TABLE EVENTREQUEST
(   --ATTR
    EVENTNO     VARCHAR2(8)   NOT NULL,
    DATEHELD    DATE          NOT NULL,
    DATEREQ     DATE          NOT NULL,
    FACNO       VARCHAR2(8)   NOT NULL,
    CUSTNO      VARCHAR2(8)   NOT NULL,
    DATEAUTH    DATE          NULL,
    STATUS      VARCHAR2(25)  NOT NULL,
    ESTCOST     NUMERIC       NOT NULL,
    ESTAUDIENCE INT           NOT NULL,
    BUDNO       VARCHAR2(8)   NULL,
    --KEY
    PRIMARY KEY(EVENTNO),
    FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO),
    FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
    --CHECK
    CONSTRAINT CHECK_STATUS_ENUM
        CHECK(STATUS IN ('Approved','Pending','Denied')),
    CONSTRAINT CHECK_ESTAUDIENCE_OVER_0
        CHECK(ESTAUDIENCE > 0)
);