--TABLE
CREATE TABLE EVENTPLANLINE
(   --ATTR
    PLANNO    VARCHAR2(8) NOT NULL,
    LINENO    INT         NOT NULL,
    TIMESTART DATE        NOT NULL,
    TIMEEND   DATE        NOT NULL,
    NUMBERFLD INT         NOT NULL,
    LOCNO     VARCHAR2(8) NOT NULL,
    RESNO     VARCHAR2(8) NOT NULL,
    --KEY
    CONSTRAINT PK_EVNTPLLIN PRIMARY KEY(PLANNO,LINENO),
    FOREIGN KEY (PLANNO) REFERENCES EVENTPLAN(PLANNO),
    FOREIGN KEY (LOCNO) REFERENCES LOCATION(LOCNO),
    FOREIGN KEY (RESNO) REFERENCES RESOURCETBL(RESNO),
    --CHECK
      CONSTRAINT CHECK_TIME_START_LESS_THAN_END
        CHECK(TIMESTART < TIMEEND)
);