--TABLE
CREATE TABLE EVENTPLAN
(   --ATTR
    PLANNO    VARCHAR2(8)   NOT NULL,
    EVENTNO   VARCHAR2(8)   NOT NULL,
    WORKDATE  DATE          NOT NULL,
    NOTES     VARCHAR2(255) NULL,
    ACTIVITY  VARCHAR2(25)  NOT NULL,
    EMPNO     VARCHAR2(8)   NULL,
    --KEY
    PRIMARY KEY(PLANNO),
    FOREIGN KEY (EVENTNO) REFERENCES EVENTREQUEST(EVENTNO),
    FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO),
    --CHECK
      CONSTRAINT CHECK_ACTIVITY_OPTIONS
        CHECK(ACTIVITY IN ('Operation','Cleanup','Setup'))
);