--TABLE
CREATE TABLE FACILITY
(   --ATTR
    FACNO     VARCHAR2(8) NOT NULL,
    FACNAME   VARCHAR(50) NOT NULL,
    --KEY
    PRIMARY KEY (FACNO),
    --CHECK
    CONSTRAINT UQ_FACNAME UNIQUE (FACNAME)
);
