--TABLE
CREATE TABLE LOCATION
(   --ATTR
    LOCNO   VARCHAR2(8) NOT NULL,
    FACNO   VARCHAR2(8) NOT NULL,
    LOCNAME VARCHAR(50) NOT NULL,
    --KEY
    PRIMARY KEY (LOCNO),
    FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO)
    --CHECK
);
