--TABLE
CREATE TABLE RESOURCETBL
(   --ATTR
    RESNO   VARCHAR(8)    NOT NULL,
    RESNAME VARCHAR(100)  NOT NULL,
    RATE    NUMERIC       NOT NULL,
    --KEY
    PRIMARY KEY(RESNO),
    --CHECK
    CONSTRAINT CHECK_RATE_OVER_0
        CHECK(RATE > 0)
);
