--Q#1
SELECT DISTINCT CITY 
                ,STATE
                ,ZIP
FROM CUSTOMER;

--Q#2
SELECT EMPNAME
        ,DEPARTMENT
        ,PHONE
        ,EMAIL
FROM EMPLOYEE
WHERE PHONE LIKE '3-%';


--Q#3
SELECT *
FROM RESOURCETBL
WHERE RATE BETWEEN 10 AND 20;

--Q#4
SELECT EVENTNO
        ,DATEAUTH
        ,STATUS
FROM EVENTREQUEST
WHERE (STATUS = 'Approved' OR STATUS = 'Denied')
        AND EXTRACT(YEAR FROM DATEAUTH) = 2013
        AND EXTRACT(MONTH FROM DATEAUTH) = 7;

--Q#5
SELECT LOCNO
        ,LOCNAME
        ,FACILITY.*
FROM LOCATION
        JOIN FACILITY ON LOCATION.FACNO=FACILITY.FACNO
WHERE FACILITY.FACNAME = 'Basketball arena';

--Q#6
SELECT EVENTPLAN.PLANNO
        ,COUNT(EVENTPLANLINE.LINENO) COUNT_PLANLINE
        ,SUM(EVENTPLANLINE.NUMBERFLD) SUM_NUBMERFLD
FROM EVENTPLAN
      JOIN EVENTPLANLINE ON EVENTPLAN.PLANNO=EVENTPLANLINE.PLANNO
GROUP BY EVENTPLAN.PLANNO;

