-- Note that th... *** SQLINES FOR EVALUATION USE ONLY *** 
-- other tables... *** SQLINES FOR EVALUATION USE ONLY *** 

-- Drop tables
-- You only nee... *** SQLINES FOR EVALUATION USE ONLY *** 

/* SQLINES EVALUATION VERSION TRUNCATES VARIABLE NAMES AND COMMENTS. */
/* OBTAIN A LICENSE AT WWW.SQLINES.COM FOR FULL CONVERSION. THANK YOU. */

DROP TABLE SSSales;

DROP TABLE SSCustomer;

DROP TABLE SSItem;

DROP TABLE SSStore;

DROP TABLE SSDivision;

DROP TABLE SSTimeDim;



-- Drop sequenc... *** SQLINES FOR EVALUATION USE ONLY *** 
-- Only necessa... *** SQLINES FOR EVALUATION USE ONLY *** 

DROP SEQUENCE SSTimeNoSeq;

DROP SEQUENCE SSSalesNoSeq;



CREATE TABLE SSCustomer

( 	CustId 	        CHAR(8) NOT NULL,

  	CustName	VARCHAR(30) NOT NULL,

        CustPhone    	VARCHAR(15) NOT NULL,

	CustStreet	VARCHAR(50) NOT NULL,

	CustCity	VARCHAR(30) NOT NULL,

   	CustState	VARCHAR(20) NOT NULL,

   	CustZip		VARCHAR(10) NOT NULL,

	CustNation	VARCHAR(20) NOT NULL,

 CONSTRAINT PKSSCustomer PRIMARY KEY (CustId)  );




CREATE TABLE SSDivision

( 	DivId 	 	CHAR(8) NOT NULL,

	DivName		VARCHAR(50) NOT NULL,

  	DivManager	VARCHAR(30) NOT NULL,

 CONSTRAINT PKSSDivision PRIMARY KEY (DivId) );




CREATE TABLE SSStore

( 	StoreId 	CHAR(8) NOT NULL,

	DivId		CHAR(8) NOT NULL,

  	StoreManager	VARCHAR(30) NOT NULL,

	StoreStreet	VARCHAR(50) NOT NULL,

	StoreCity	VARCHAR(30) NOT NULL,

   	StoreState	VARCHAR(20) NOT NULL,

   	StoreZip	VARCHAR(10) NOT NULL,

	StoreNation	VARCHAR(20) NOT NULL,

 CONSTRAINT PKSSStore PRIMARY KEY (StoreId),

 CONSTRAINT FKSSDivId FOREIGN KEY (DivId) REFERENCES SSDivision );




CREATE TABLE SSItem

( 	ItemId 	   	CHAR(8) NOT NULL,

  	ItemName	VARCHAR(30) NOT NULL,

	ItemBrand	VARCHAR(30) NOT NULL,

   	ItemCategory	VARCHAR(30) NOT NULL,

  	ItemUnitPrice	DECIMAL(12,2) NOT NULL,

CONSTRAINT PKSSItem PRIMARY KEY (ItemId) );

-- In my experi... *** SQLINES FOR EVALUATION USE ONLY *** 

-- On an Oracle... *** SQLINES FOR EVALUATION USE ONLY *** 
-- generates fi... *** SQLINES FOR EVALUATION USE ONLY *** 
-- problem. On ... *** SQLINES FOR EVALUATION USE ONLY *** 
-- I suggest th... *** SQLINES FOR EVALUATION USE ONLY *** 

CREATE SEQUENCE SSTimeNoSeq
MINVALUE 1
START WITH 1;

-- Try using 0 ... *** SQLINES FOR EVALUATION USE ONLY *** 

-- CREATE SEQUE... *** SQLINES FOR EVALUATION USE ONLY *** 
-- MINVALUE 0
-- START WITH 0... *** SQLINES FOR EVALUATION USE ONLY *** 

CREATE TABLE SSTimeDim

( 	TimeNo 	        DECIMAL(38) NOT NULL,

  	TimeDay		DECIMAL(38) NOT NULL,

  	TimeMonth	DECIMAL(38) NOT NULL,

  	TimeQuarter	DECIMAL(38) NOT NULL,

  	TimeYear	DECIMAL(38) NOT NULL,

  	TimeDayofWeek	DECIMAL(38) NOT NULL,

  	TimeFiscalYear	DECIMAL(38) NOT NULL,

 CONSTRAINT PKSSTime PRIMARY KEY (TimeNo),

 CONSTRAINT SSTimeDay1 CHECK (TimeDay BETWEEN 1 AND 31),

 CONSTRAINT SSTimeMonth1 CHECK (TimeMonth BETWEEN 1 AND 12),

 CONSTRAINT SSTimeQuarter1 CHECK (TimeQuarter BETWEEN 1 AND 4),

 CONSTRAINT SSTimeDayOfWeek1 CHECK (TimeDayOfWeek BETWEEN 1 AND 7) );


-- In my experi... *** SQLINES FOR EVALUATION USE ONLY *** 

-- On an Oracle... *** SQLINES FOR EVALUATION USE ONLY *** 
-- generates fi... *** SQLINES FOR EVALUATION USE ONLY *** 
-- problem. On ... *** SQLINES FOR EVALUATION USE ONLY *** 
-- I suggest th... *** SQLINES FOR EVALUATION USE ONLY *** 

CREATE SEQUENCE SSSalesNoSeq
MINVALUE 1
START WITH 1;

-- Try using 0 ... *** SQLINES FOR EVALUATION USE ONLY *** 

-- CREATE SEQUE... *** SQLINES FOR EVALUATION USE ONLY *** 
-- MINVALUE 0
-- START WITH 0... *** SQLINES FOR EVALUATION USE ONLY *** 

CREATE TABLE SSSales

( 	SalesNo 	DECIMAL(38) NOT NULL,

  	SalesUnits	DECIMAL(38) NOT NULL,

        SalesDollar    	DECIMAL(12,2) NOT NULL,

	SalesCost	DECIMAL(12,2) NOT NULL,

	CustId		CHAR(8) NOT NULL,

	ItemId		CHAR(8) NOT NULL,

	StoreId		CHAR(8) NOT NULL,

	TimeNo		DECIMAL(38) NOT NULL,

 CONSTRAINT PKSSSales PRIMARY KEY (SalesNo),

 CONSTRAINT FKSSCustId FOREIGN KEY (CustId) REFERENCES SSCustomer,

 CONSTRAINT FKSSItemId FOREIGN KEY (ItemId) REFERENCES SSItem,

 CONSTRAINT FKSSStoreId FOREIGN KEY (StoreId) REFERENCES SSStore,

 CONSTRAINT FKSSTimeId FOREIGN KEY (TimeNo) REFERENCES SSTimeDim );






