--Query 1: Sales Order Shipments by Month and Category Code1

SELECT 
  DD.CALMONTH,
  CVD.ADDRCATCODE1,
  SUM(EXTCOST),
  SUM(QUANTITY)
FROM INVENTORY_FACT INF
        JOIN DATE_DIM DD ON INF.DATEKEY=DD.DATEKEY
        JOIN CUST_VENDOR_DIM CVD ON INF.CUSTVENDORKEY=CVD.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5
        AND DD.CALYEAR = 2011
GROUP BY CUBE(DD.CALMONTH,CVD.ADDRCATCODE1);