--Query 2: Sales Order Shipments by Name, Zip, and Quarter
--INCORRECT
SELECT  DD.CALQUARTER,
        CVD.ZIP,
        CVD.NAME,
        SUM(EXTCOST),
        COUNT(*)
FROM INVENTORY_FACT INF
        JOIN DATE_DIM DD ON INF.DATEKEY=DD.DATEKEY
        JOIN CUST_VENDOR_DIM CVD ON INF.CUSTVENDORKEY=CVD.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5
        AND (DD.CALYEAR = 2011 OR DD.CALYEAR = 2012)
GROUP BY ROLLUP(DD.CALQUARTER,CVD.ZIP,CVD.NAME)
ORDER BY DD.CALQUARTER,CVD.ZIP,CVD.NAME;