--Query 3: Transfers by Company and Branch Plant

SELECT 
  CD.COMPANYNAME,
  BPD.BPNAME,
  SUM(EXTCOST),
  SUM(QUANTITY)
FROM INVENTORY_FACT INF
        JOIN BRANCH_PLANT_DIM BPD ON BPD.BRANCHPLANTKEY=INF.BRANCHPLANTKEY
        JOIN COMPANY_DIM CD ON CD.COMPANYKEY=BPD.COMPANYKEY
WHERE TRANSTYPEKEY = 2
GROUP BY ROLLUP(CD.COMPANYNAME,BPD.BPNAME)
ORDER BY CD.COMPANYNAME,BPD.BPNAME;